# Generated by Django 4.1.4 on 2023-01-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app31", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="user",),
    ]
