# Generated by Django 4.1.4 on 2023-01-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app31", "0002_remove_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(max_length=100),
        ),
    ]
